#!/usr/bin/env python

import sys
import csv
from operator import itemgetter
import locale

if len(sys.argv) < 2:
    sys.exit("Usage: " + sys.argv[0] + " <profile>")

with open(sys.argv[1]) as tsv:
    lines = []
    totalWords = 0
    for line in csv.reader(tsv, dialect="excel-tab"):
        lines.append([int(line[0]), int(line[1])])
        totalWords += int(line[1])

    lines.sort(reverse=True, key=itemgetter(1))

    # Print output
    locale.setlocale(locale.LC_ALL, 'en_US')
    print "Total: " + locale.format("%d", totalWords, grouping=True) + " words"
    print "Instr\tWords\t% of total"
    print "-----\t-----\t----------"
    for line in lines:
        print ("%d" % line[0] + "\t" + "%d" % line[1] + "\t" +
               "%.2f" % (float(line[1]) * 100.0 / totalWords) + "%")
